### ISSUE TITLE
Week 4 Review Ticket

### ISSUE THREAD

**Issue by xXAASXx** [xXAASXx/Armaan-Shamsaasef-2-#6]
# Score: 6/5 
## Peer Evaluation by Derick Huang

# Accounts and Logins

## [Armaan College Board Create Task](https://github.com/xXAASXx/Armaan-Shamsaasef-2-/blob/main/createtask.md)

- [x] CB Create Task Coding requirements documented

- [x] Runtime of Code(with comments) on Replit/Intellij

### Accounts and Logins Challenges/Hacks ( 3 Points - Team)

- Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.

- Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.

- [x] Hack#1 Add Phone Number to Sign Up / Authorization screen

- [x] Hack#2 Add logout to CRUD screen

- [x] Hack#3 Add login_required to another portion of the project

- [x] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by Pitsco** [comment]
Score: 6/5

All requirements were met and the hacks were shown working as well. The extra credit was good and I love the design of the website. Also having it be checked by Mr. Mortensen made it a lot easier to grade and less comments for me to add. Last but not least amazing job on the Create Task as the wish list is something you can use on everything.
